#pragma once

const float SPATIALLABS_SCREEN_WIDTH_CM = 34.42176;
const float SPATIALLABS_SCREEN_HEIGHT_CM = 19.36224;
const int SPATIALLABS_SCREEN_RESOLUTION_WIDTH = 3840;
const int SPATIALLABS_SCREEN_RESOLUTION_HEIGHT = 2160;